export const Constants = {
    apiLogin: '/auth/login',
    apiCustomer: '/cliente',
    apiParamStaticDept: '/parametroEstatico/departamentos',
    apiParamStaticCitiesByDept: '/parametroEstatico/municipiosPorDepartamento',
    apiParamsByType: '/parametro/tipo',
    apiCustomerCommercialInfo: '/informacionComercial',
    apiCustomerBuilding: '/obra/cliente',
    apiBuilding: '/obra',
    apiTransportersByClient:'/transportador/cliente',
    apiShippingRateByClient: '/tarifaFlete/cliente',
    apiShippingRateByTransporter: '/tarifaFlete/transportador',
    apiRoutesByTransporter: '/ruta/Transportador',
    apiDocsByTransporter: '/documento/documentosTransportador',
    apiVehiclesByTransporter: '/vehiculo/transportador',
    apiDriversByTransporter: '/conductor/Transportador',
    apiRateShipping: '/tarifaFlete/cliente',
    apiCustomerRateShipping: '/tarifaFlete/cliente',
    apiTransporterRateShipping: '/tarifaFlete/transportador',
    apiTransporter: '/transportador',
    apiLinkClientTransporter:'/cliente/linkClienteTransportador',
    apiAuthorizeTransporter:'/cliente/autorizarTransportador',
    apiSendTransporterCode:'/cliente/codigoVerificacionTransportador',
    apiTransporterRoute: '/ruta/transportador',
    apiRoute: '/ruta',
    apiVehicle: '/vehiculo',
    apiLinkTransporterVehicle:'/transportador/vehiculo',
    apiAuthorizeVehicle:'/transportador/autorizarVehiculo',
    apiSendVehicleCode:'/transportador/codigoVerificacionVehiculo',
    apiLinkTransporterDriver:'/conductor/linkConductorTransportador',
    apiDriver: '/conductor',
    apiDriverGeneralInfo: '/conductor/infoGeneral',
    apiTransporterDocument: '/documento/documentoTransportador',
    apiDriverDocument: '/documento/documentoConductor',
    apiDocsByDriver: '/documento/documentosConductor',
    apiDriverIsRelated: '/conductor/esRelacionado',
    apiDeleteTransporterDriver: '/conductor/eliminarConductorTransportador',
    apiThirdParty: '/tercero/numeroDocumento',
    apiAllThirdParties: '/tercero',
    apiThirdPartyPersonalInfo: '/tercero/infoPersonal',
    apiUploadTransporterDoc: '/upload/transportador/archivo',
    apiUploadDriverDoc: '/upload/Conductor/archivo',
    apiUploadDriverImage: '/upload/Conductor/imagen',
    apiAuthRegister: '/auth/registro',
    apiAuthUsers: '/auth/usuario',
    apiAuthResetPassword: '/auth/cambiarContrasena',
    apiAuthProfiles: '/auth/perfil',
    apiAuthProfileModule: '/modulo/perfil',
    apiAuthProfileModulePut: '/modulo/perfilModulo',
    apiDownloadDoc: '/download/documento',
    apiParams: '/parametro',
    apiParamType: '/tipoParametro',
    apiDeleteCustomerTransporter: '/cliente/transportador',
    apiDeleteTransporterVehicle: '/transportador/vehiculo',
    apiMaterial: '/material',
    apiProvider: '/proveedor',
    apiProviderPrices: '/precioMaterialProveedor',
    apiProviderTimes: '/tiempoCargueProveedor',
    apiMaterialVehicle: '/material/vehiculo',
    apiLinkMaterialsVehicle: '/material/linkMaterialesVehiculo',
    pathHome: 'home',
    pathLogin: 'login',
    numRowMax: 2147483647
};
