export const Constants = {
    apiLogin: '/auth/login',
    apiRecovery: '/auth/recuperarContrasena',
    apiChangePw: '/auth/cambiarContrasena',
    apiCustomer: '/cliente',
    apiCustomerList: '/cliente/lista',
    apiParamStaticDept: '/parametroEstatico/departamentos',
    apiParamStaticCitiesByDept: '/parametroEstatico/municipiosPorDepartamento',
    apiParamsByType: '/parametro/tipo',
    apiCustomerCommercialInfo: '/informacionComercial',
    apiCustomerBuilding: '/obra/cliente',
    apiCustomerBuildingOrder: '/obra/clienteListaPedido',
    apiBuilding: '/obra',
    apiTransportersByClient:'/transportador/cliente',
    apiShippingRateByClient: '/clienteTarifaFlete',
    apiShippingRateByTransporter: '/transportadorTarifaFlete',
    apiRoutesByTransporter: '/ruta/Transportador',
    apiDocsByTransporter: '/documento/documentosTransportador',
    apiVehiclesByTransporter: '/vehiculo/transportador',
    apiDriversByTransporter: '/conductor/Transportador',
    apiRateShipping: '/clienteTarifaFlete',
    apiCustomerRateShipping: '/clienteTarifaFlete',
    apiTransporterRateShipping: '/transportadorTarifaFlete',
    apiTransporter: '/transportador',
    apiLinkClientTransporter:'/cliente/linkClienteTransportador',
    apiAuthorizeTransporter:'/cliente/autorizarTransportador',
    apiSendTransporterCode:'/cliente/codigoVerificacionTransportador',
    apiTransporterRoute: '/ruta/transportador',
    apiRoute: '/ruta',
    apiVehicle: '/vehiculo',
    apiVehiclePlate: '/vehiculo/placa',
    apiLinkTransporterVehicle:'/transportador/vehiculo',
    apiAuthorizeVehicle:'/transportador/autorizarVehiculo',
    apiSendVehicleCode:'/transportador/codigoVerificacionVehiculo',
    apiLinkTransporterDriver:'/conductor/linkConductorTransportador',
    apiDriver: '/conductor',
    apiDriverGeneralInfo: '/conductor/infoGeneral',
    apiTransporterDocument: '/documento/documentoTransportador',
    apiDriverDocument: '/documento/documentoConductor',
    apiDocsByDriver: '/documento/documentosConductor',
    apiDriverIsRelated: '/conductor/esRelacionado',
    apiDeleteTransporterDriver: '/conductor/eliminarConductorTransportador',
    apiThirdParty: '/tercero/numeroDocumento',
    apiAllThirdParties: '/tercero',
    apiThirdPartyPersonalInfo: '/tercero/infoPersonal',
    apiUploadTransporterDoc: '/upload/transportador/archivo',
    apiUploadDriverDoc: '/upload/Conductor/archivo',
    apiUploadDriverImage: '/upload/Conductor/imagen',
    apiAuthRegister: '/auth/registro',
    apiAuthUsers: '/auth/usuario',
    apiAuthResetPassword: '/auth/cambiarContrasena',
    apiAuthProfiles: '/auth/perfil',
    apiAuthProfileModule: '/modulo/perfil',
    apiAuthProfileModulePut: '/modulo/perfilModulo',
    apiDownloadDoc: '/download/documento',
    apiParams: '/parametro',
    apiParamType: '/tipoParametro',
    apiDeleteCustomerTransporter: '/cliente/transportador',
    apiDeleteTransporterVehicle: '/transportador/vehiculo',
    apiMaterial: '/material',
    apiMaterialOrder: '/material/listaPedido',
    apiProvider: '/proveedor',
    apiProviderPrices: '/precioMaterialProveedor',
    apiProviderTimes: '/tiempoCargueProveedor',
    apiProviderFactories: '/planta/proveedor',
    apiFactories: '/planta',
    apiMaterialVehicle: '/material/vehiculo',
    apiLinkMaterialsVehicle: '/material/linkMaterialesVehiculo',
    apiDriverVehicle: '/conductor/vehiculo',
    apiLinkDriverVehicle: '/conductor/linkConductorVehiculo',
    apiDriverRelatedToVehicle: '/conductor/esRelacionadoVehiculo',
    apiDocsByVehicle: '/documento/documentosVehiculo',
    apiVehicleDocument: '/documento/documentoVehiculo',
    apiUploadVehicleDoc: '/upload/vehiculo/archivo',
    apiRestrictedDestination: '/destinoRestringido/lista',
    apiRestrictedDestinationByVehicle: '/destinoRestringido/vehiculo',
    apiLinkRestrictedDestinationVehicle: '/destinoRestringido/linkVehiculoDestinoRestringido',
    apiRateTransport: '/tarifaTransporte',
    apiRouteList: '/ruta/lista',
    apiOrder: '/pedido',
    apiOrderApprove: '/pedido/aprobar',
    apiProviderOrder: '/PedidoProveedor',
    apiPreassignment: '/preasignacion',
    apiPreassignmentByPlate: '/preasignacion/placa',
    apiPreassignmentApprove: '/preasignacion/aprobar',
    apiPreassignmentReject: '/preasignacion/rechazar',
    apiCustomerPlate: '/cliente/placasTransportadores',
    pathHome: 'home',
    pathLogin: 'login',
    numRowMax: 2147483647
};
