export interface order {
    id?: number,
    startDate?: Date,
    buildingId?: number,
    buildingName?: string,
    materialId?: number,
    materialName?: number,
    clientId?: number,
    clientName?: string,
    monday?: number,
    tuesday?: number,
    wednesday?: number,
    thursday?: number,
    friday?: number,
    saturday?: number,
    sunday?: number,
    totalAmount?: number,
    aprobeAmount?: number,
    state?: string
}